### ISSUE TITLE
Создание стикеров в центре страницы.

### ISSUE THREAD

**Issue by Antonowka** [Antonowka/habit-tracker#29]
- [x] Создание стикеров +- в центре страницы => (50% топ 50% лефт) +- @max7394 
   - [x]  Создание стикера по центру экрана, на уровне кнопок.

- [x] добавить события тача от 810px и ниже, для перетаскивания хабитов на мобилках и падах. @max7394

**Comment by Antonowka** [comment]
![Image](https://user-images.githubusercontent.com/102463034/220210900-b9dff0f8-9015-425a-8fef-5414cb634a08.png)

**Comment by max7394** [comment]
Добавлено создание записки по центру экрана
Добавлена поддержка тач-устройств
